 - name: ZAP Baseline Scan
  uses: zaproxy/action-baseline@v0.11.0
  with:
    # GitHub Token to create issues in the repository
    token: ${{ github.token }} # Optional. Defaults to using the GitHub token associated with the workflow.
    # Target URL
    target: https://juice-shop.herokuapp.com/# 
    # Relative path of the ZAP configuration file
    rules_file_name: # Optional. You can specify a rules file if needed.
    # The Docker file to be executed
    docker_name: ghcr.io/zaproxy/zaproxy:stable # Optional. Defaults to using the stable version of ZAP from GitHub Container Registry.
    # Additional command line options
    cmd_options: # Optional. You can provide additional command-line options to ZAP.
    # The title for the GitHub issue to be created
    issue_title: ZAP Scan Baseline Report # Optional. Defaults to "ZAP Scan Baseline Report".
    # The action status will be set to fail if ZAP identifies any alerts during the baseline scan
    fail_action: # Optional. You can specify whether the action should fail if ZAP identifies any alerts. 
    # The action will file the report to the GitHub issue using the issue_title input
    allow_issue_writing: true # Optional. Specifies whether the action is allowed to write the report to a GitHub issue. Defaults to true.
    # The name of the artifact that contains the ZAP reports
    artifact_name: zap_scan # Optional. Specifies the name of the artifact that will contain the ZAP reports. Defaults to "zap_scan".
